title: KleeBlatt.Games - Development Update Page
description: Linking WAX Blockchain with Offerwall networks while offering guidance for new users and introducing cross-selling opportunities for existing WAX projects
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
